"""
estimate_feedback_law.py  —  CADENCE pipeline, Module 3
=======================================================
Recover a dwell-dependent exit-hazard law from CAUSALLY DECODED synthetic states:

        P(SUSTAINED_HIGH -> REFRACTORY | L) = sigmoid(b0 + b1 * L)

`b1 > 0` means exit probability rises with recent time spent in the synthetic
high state. Because L is reconstructed from those state labels, this alone does
NOT identify a biochemical calcium-load mechanism. Recovering b1 from data
generated by a known law validates the estimator under this simulator; it is
not biological evidence.

WHY A LOAD VARIABLE AT ALL (the semi-Markov problem)
-----------------------------------------------------
A plain HMM has a CONSTANT transition matrix: P(high -> refractory) is the same
whether the cell just entered the high state or has been stuck there for a
minute. That cannot represent the cumulative hazard encoded by this simulator.
Rather than abandon the HMM, we keep it for state *estimation* and model the
exit hazard explicitly as a function of recent high-state exposure:

    L[t] = decay * L[t-1] + 1{state[t] == SUSTAINED_HIGH}

This is a causal exponential accumulator: it rises while the cell is in the high
state and decays otherwise. It is a causal dwell-history proxy: it uses only
past and present frames, never the future. Calling it a measured calcium load
would exceed what the variable contains.

CHOOSING ONE COMPARABLE SCALE
-----------------------------
The main intact-versus-blocked exploratory analysis fixes one shared decay
(0.90) for both conditions. This value was standardized during repository
auditing, not prospectively preregistered. Selecting decay separately changes
the predictor scale, making the resulting slopes incomparable.

INFERENCE
---------
Logistic regression by maximum likelihood, hand-implemented on scipy.optimize
(sklearn is outside the dependency budget). Two uncertainty estimates:

  1) Wald CI from the inverse observed-information matrix. Fast, but it assumes
     every frame is an independent observation, which is FALSE here — frames
     within a trace are strongly autocorrelated, so Wald CIs are too narrow.
  2) CLUSTER BOOTSTRAP over whole simulated traces (resample traces with
     replacement, refit both coefficients). This respects the synthetic data's
     independent unit. Real experiments require animal- or preparation-level
     clustering instead. This is the CI reported as primary.

STATE-ESTIMATION ERROR (reported, not hidden)
---------------------------------------------
State-estimation errors can bias the slope. We therefore print three clearly
labelled quantities:

    (a) from CAUSAL states    -> matches the controller's online information set
    (b) from TRUE states      -> an oracle upper bound; isolates how much damage
                                 state-estimation error alone is doing
    (c) ground-truth b1        -> the number the simulator actually used

NOTE ON SCOPE: this comparison checks whether the pipeline recovers a contrast
deliberately encoded in synthetic data. It is a benchmark result, not an
independent falsification of the biological hypothesis.
"""

import argparse
import json
import os

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.optimize import minimize

STATE_NAMES = ["QUIESCENT", "OSCILLATORY", "SUSTAINED_HIGH", "REFRACTORY"]
HIGH, REFRACTORY = 2, 3

# Ground truth baked into generate_synthetic.py, for reporting only - never used
# to fit anything.
TRUE_BETA1 = {"intact": 0.9, "blocked": 0.02}
TRUE_BETA0 = -3.0


# --------------------------------------------------------------------------- #
# Load accumulator
# --------------------------------------------------------------------------- #
def compute_load(states, decay):
    """
    Causal exponential accumulator over time spent in SUSTAINED_HIGH.

        L[t] = decay * L[t-1] + 1{states[t] == HIGH}

    Returns L aligned with `states`. L[t] includes the current frame's
    contribution, matching the simulator's convention (the load that is "in
    effect" when the cell decides whether to switch off at frame t).
    """
    L = np.empty(len(states), dtype=float)
    acc = 0.0
    for t, s in enumerate(states):
        acc = acc * decay + (1.0 if s == HIGH else 0.0)
        L[t] = acc
    return L


def build_transition_dataset(df, state_col, decay):
    """
    Extract the (load, did_it_switch_off) pairs the logistic model is fit to.

    We look ONLY at frames where the cell is currently in SUSTAINED_HIGH — those
    are the frames at which the feedback law is defined — and ask whether the
    NEXT frame is REFRACTORY.

    Returns (L, y, trace_ids) where trace_ids is kept so the bootstrap can
    resample whole simulated traces.
    """
    if "model_split" in df.columns and (df["model_split"] == "held_out").any():
        df = df[df["model_split"] != "fit"]

    Ls, ys, tids = [], [], []
    for tid, g in df.groupby("trace_id", sort=True):
        g = g.sort_values("time_s")
        s = g[state_col].to_numpy()
        L = compute_load(s, decay)

        at_high = s[:-1] == HIGH               # frames where the law applies
        if not at_high.any():
            continue
        switched = (s[1:] == REFRACTORY)       # did it switch off next frame?
        Ls.append(L[:-1][at_high])
        ys.append(switched[at_high].astype(float))
        tids.append(np.full(at_high.sum(), tid))

    if not Ls:
        return np.array([]), np.array([]), np.array([])
    return np.concatenate(Ls), np.concatenate(ys), np.concatenate(tids)


# --------------------------------------------------------------------------- #
# Logistic regression by maximum likelihood
# --------------------------------------------------------------------------- #
def _nll_and_grad(beta, X, y):
    """
    Negative log-likelihood and gradient for logistic regression.
    Uses logaddexp for numerical stability instead of log(1+exp(z)) directly.
    """
    z = X @ beta
    nll = np.sum(np.logaddexp(0.0, z) - y * z)
    p = 1.0 / (1.0 + np.exp(-z))
    grad = X.T @ (p - y)
    return nll, grad


def fit_logistic(L, y):
    """
    MLE fit of P(y=1 | L) = sigmoid(b0 + b1*L).
    Returns (beta, loglik, cov) where cov is the inverse observed information
    (used for the Wald CI).
    """
    X = np.column_stack([np.ones_like(L), L])
    res = minimize(_nll_and_grad, np.zeros(2), args=(X, y),
                   jac=True, method="BFGS")
    if not np.isfinite(res.fun) or not np.all(np.isfinite(res.x)):
        raise RuntimeError("logistic optimizer returned a non-finite solution")
    # BFGS can report precision loss near a good solution. Reject only failures
    # whose score is also materially away from a stationary point.
    if not res.success and np.linalg.norm(res.jac) > 1e-4:
        raise RuntimeError(f"logistic optimizer failed: {res.message}")
    beta = res.x
    loglik = -res.fun

    # observed information: X' W X, with W = diag(p(1-p))
    z = X @ beta
    p = 1.0 / (1.0 + np.exp(-z))
    W = p * (1.0 - p)
    info = X.T @ (X * W[:, None])
    try:
        cov = np.linalg.inv(info)
    except np.linalg.LinAlgError:
        cov = np.full((2, 2), np.nan)
    return beta, loglik, cov


def select_decay(df, state_col, grid):
    """
    Choose the load decay by profile likelihood: refit the logistic model at each
    candidate decay and keep the best-fitting one. This is how we avoid smuggling
    in the simulator's 0.92.
    """
    best = (None, -np.inf, None)
    for d in grid:
        L, y, _ = build_transition_dataset(df, state_col, d)
        if len(L) < 20 or y.sum() < 5:
            continue
        _, ll, _ = fit_logistic(L, y)
        if ll > best[1]:
            best = (d, ll, None)
    return best[0]


def bootstrap_coefficients(df, state_col, decay, n_boot=400, seed=0):
    """
    CLUSTER bootstrap: resample whole traces with replacement and refit.

    Frames within a trace are autocorrelated, so treating frames as the
    resampling unit would badly understate uncertainty. Synthetic traces are
    independent by construction, so traces are the resampling unit here.
    """
    if "model_split" in df.columns and (df["model_split"] == "held_out").any():
        df = df[df["model_split"] != "fit"]

    rng = np.random.default_rng(seed)
    trace_ids = df["trace_id"].unique()
    by_trace = {tid: g for tid, g in df.groupby("trace_id", sort=True)}

    out = []
    for _ in range(n_boot):
        picked = rng.choice(trace_ids, size=len(trace_ids), replace=True)
        # relabel so repeated draws are treated as distinct cells
        parts = []
        for new_id, tid in enumerate(picked):
            g = by_trace[tid].copy()
            g["trace_id"] = new_id
            parts.append(g)
        boot_df = pd.concat(parts, ignore_index=True)

        L, y, _ = build_transition_dataset(boot_df, state_col, decay)
        if len(L) < 20 or y.sum() < 3:
            continue
        try:
            beta, _, _ = fit_logistic(L, y)
        except RuntimeError:
            continue
        out.append(beta)
    return np.asarray(out, dtype=float).reshape(-1, 2)


def bootstrap_b1(df, state_col, decay, n_boot=400, seed=0):
    """Backward-compatible view of the cluster bootstrap's slope draws."""
    return bootstrap_coefficients(
        df, state_col, decay, n_boot=n_boot, seed=seed
    )[:, 1]


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #
def analyse(df, condition, state_col, decay, n_boot, seed, label):
    L, y, _ = build_transition_dataset(df, state_col, decay)
    if len(L) == 0:
        print(f"  [{label}] no SUSTAINED_HIGH frames found - cannot fit.")
        return None

    beta, ll, cov = fit_logistic(L, y)
    b0, b1 = beta
    se_b1 = np.sqrt(cov[1, 1]) if np.isfinite(cov[1, 1]) else np.nan
    wald_lo, wald_hi = b1 - 1.96 * se_b1, b1 + 1.96 * se_b1

    boot_beta = bootstrap_coefficients(
        df, state_col, decay, n_boot=n_boot, seed=seed
    )
    boots = boot_beta[:, 1]
    if len(boots):
        blo, bhi = np.percentile(boots, [2.5, 97.5])
    else:
        blo = bhi = np.nan

    print(f"  [{label}]  n_high_frames={len(L)}  n_switch_events={int(y.sum())}")
    print(f"      b0 = {b0:+.3f}")
    print(f"      b1 = {b1:+.4f}   "
          f"cluster-bootstrap 95% CI [{blo:+.4f}, {bhi:+.4f}]   <-- reported")
    print(f"                        naive Wald 95% CI [{wald_lo:+.4f}, {wald_hi:+.4f}]"
          f"  (too narrow: assumes independent frames)")
    return {"condition": condition, "label": label, "b0": b0, "b1": b1,
            "boot": boots, "boot_beta": boot_beta, "ci": (blo, bhi),
            "L": L, "y": y, "decay": decay}


def plot_feedback_curves(results, out_png):
    """
    The headline figure: recovered feedback law, intact vs blocked, with
    bootstrap uncertainty and the binned empirical switch rate overlaid so the
    reader can see the fit is not just a smooth line through nothing.
    """
    fig, ax = plt.subplots(figsize=(7.4, 5.0))
    colors = {"intact": "#1f77b4", "blocked": "#d62728"}

    for r in results:
        if r is None:
            continue
        cond = r["condition"]
        c = colors.get(cond, "gray")
        L, y = r["L"], r["y"]
        grid = np.linspace(0, np.percentile(L, 99), 200)

        # Bootstrap both intercept and slope. Holding b0 fixed would make the
        # displayed band narrower than the uncertainty estimated by resampling.
        curves = []
        for b0b, b1b in r["boot_beta"]:
            curves.append(1 / (1 + np.exp(-(b0b + b1b * grid))))
        if curves:
            curves = np.array(curves)
            lo, hi = np.percentile(curves, [2.5, 97.5], axis=0)
            ax.fill_between(grid, lo, hi, color=c, alpha=0.18, lw=0)

        fit = 1 / (1 + np.exp(-(r["b0"] + r["b1"] * grid)))
        ax.plot(grid, fit, color=c, lw=2,
                label=f"{cond}: b1={r['b1']:+.3f} "
                      f"[{r['ci'][0]:+.3f}, {r['ci'][1]:+.3f}]")

        # binned empirical rate
        edges = np.linspace(0, np.percentile(L, 99), 9)
        idx = np.digitize(L, edges) - 1
        for b in range(len(edges) - 1):
            m = idx == b
            if m.sum() > 30:
                ax.plot(0.5 * (edges[b] + edges[b + 1]), y[m].mean(),
                        "o", color=c, ms=5, mec="white", mew=0.8)

    ax.set_xlabel("recent high-state exposure  L  (causal exponential accumulator)")
    ax.set_ylabel("P(SUSTAINED_HIGH -> REFRACTORY)")
    ax.set_title("Recovered negative-feedback law\n"
                 "b1 > 0 = increasing exit hazard; dots = binned empirical rate")
    ax.legend(loc="upper left", fontsize=9)
    ax.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(out_png, dpi=150)
    plt.close(fig)


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser(description="Recover the load-dependent feedback law.")
    ap.add_argument("--intact", default="data/decoded_intact.csv")
    ap.add_argument("--blocked", default="data/decoded_blocked.csv")
    ap.add_argument("--n_boot", type=int, default=400)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--decay", type=float, default=0.90,
                    help="fixed shared accumulator decay for both conditions")
    ap.add_argument("--fig_out", default="figures/feedback_law.png")
    ap.add_argument("--result_out", default="results/feedback_estimates.json")
    args = ap.parse_args()

    if not 0.0 < args.decay < 1.0:
        ap.error("--decay must be between 0 and 1")
    results_inferred, results_true = [], []

    for cond, path in (("intact", args.intact), ("blocked", args.blocked)):
        print(f"\n=== {cond} ===")
        df = pd.read_csv(path)
        if "model_split" in df.columns and cond == "intact":
            n_before = df["trace_id"].nunique()
            df = df[df["model_split"] != "fit"].copy()
            print("  excluded state-model fitting traces from downstream "
                  f"estimation ({n_before} -> {df['trace_id'].nunique()} traces)")

        # Use one shared decay so b1 has the same predictor scale in intact and
        # blocked conditions. Selecting it separately makes the slope contrast
        # mathematically incomparable. Profile selection remains available as a
        # sensitivity diagnostic through select_decay(), but is not the headline
        # analysis.
        decay = args.decay
        print(f"  fixed shared exposure decay: {decay}"
              f"   (simulator used 0.92)")

        # The two conditions use independent deterministic bootstrap streams.
        # Reusing one seed would create artificial pairing between unpaired
        # conditions when their draw arrays are subtracted below.
        condition_seed = args.seed + (0 if cond == "intact" else 1_000)
        if "causal_state" not in df:
            raise ValueError(
                f"{path} has no causal_state column; rerun recover_states.py"
            )
        r_inf = analyse(df, cond, "causal_state", decay,
                        args.n_boot, condition_seed,
                        "CAUSAL inferred states (end-to-end)")
        r_true = analyse(df, cond, "true_state", decay,
                         args.n_boot, condition_seed + 10_000,
                         "TRUE states (oracle bound)")
        print(f"      ground truth b1 used by simulator: {TRUE_BETA1[cond]:+.3f}")

        results_inferred.append(r_inf)
        results_true.append(r_true)

    # Bootstrap the slope contrast. Percentile intervals quantify uncertainty
    # under trace-level resampling; bootstrap tail proportions are deliberately
    # not reported as hypothesis-test p-values.
    print("\n=== BOOTSTRAP CONTRAST: b1_intact - b1_blocked ===")
    contrasts = {}
    for key, tag, res in (("causal", "CAUSAL inferred (end-to-end)", results_inferred),
                          ("oracle", "TRUE (oracle)", results_true)):
        a, b = res[0], res[1]
        if a is None or b is None or not len(a["boot"]) or not len(b["boot"]):
            print(f"  [{tag}] insufficient data.")
            continue
        n = min(len(a["boot"]), len(b["boot"]))
        diff = a["boot"][:n] - b["boot"][:n]
        lo, hi = np.percentile(diff, [2.5, 97.5])
        point = float(a["b1"] - b["b1"])
        print(f"  [{tag}]  difference = {point:+.4f}"
              f"   cluster-bootstrap 95% CI [{lo:+.4f}, {hi:+.4f}]")
        verdict = "RESOLVED" if lo > 0 else "NOT resolved"
        print(f"      -> positive synthetic contrast {verdict} "
              f"(CI {'excludes' if lo > 0 else 'includes'} zero)")
        contrasts[key] = {
            "b1_intact_minus_blocked": point,
            "ci95": [float(lo), float(hi)],
            "bootstrap_draws": int(n),
        }

    causal_blocked = results_inferred[1]
    oracle_blocked = results_true[1]
    blocked_bias_flag = bool(
        causal_blocked is not None
        and oracle_blocked is not None
        and not (causal_blocked["ci"][0] <= 0 <= causal_blocked["ci"][1])
        and oracle_blocked["ci"][0] <= 0 <= oracle_blocked["ci"][1]
    )
    if blocked_bias_flag:
        print(
            "\nCAUTION: the causal hard-state decoder resolves a small slope in "
            "the blocked arm while the oracle-state interval includes zero. "
            "Treat this as decoder-induced null bias, not feedback evidence."
        )

    os.makedirs(os.path.dirname(args.fig_out), exist_ok=True)
    plot_feedback_curves([r for r in results_inferred if r], args.fig_out)
    print(f"\nwrote {args.fig_out}")
    payload = {
        "schema_version": 2,
        "analysis_scope": (
            "synthetic estimator benchmark; not evidence of a biochemical mechanism"
        ),
        "shared_decay": args.decay,
        "diagnostics": {
            "blocked_causal_null_bias": blocked_bias_flag,
            "interpretation": (
                "causal hard-state decoding can bias the near-null blocked slope; "
                "the intact-minus-blocked contrast remains the primary synthetic result"
            ),
        },
        "contrasts": contrasts,
        "causal": {
            r["condition"]: {
                "b0": r["b0"],
                "b1": r["b1"],
                "b1_ci95": list(r["ci"]),
                "n_high_frames": int(len(r["L"])),
                "n_switch_events": int(r["y"].sum()),
            }
            for r in results_inferred if r is not None
        },
        "oracle": {
            r["condition"]: {
                "b0": r["b0"],
                "b1": r["b1"],
                "b1_ci95": list(r["ci"]),
            }
            for r in results_true if r is not None
        },
    }
    result_dir = os.path.dirname(args.result_out)
    if result_dir:
        os.makedirs(result_dir, exist_ok=True)
    with open(args.result_out, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")
    print(f"wrote {args.result_out}")
    print("Module 3 complete. Next: controller.py (CADENCE control policy).")


if __name__ == "__main__":
    main()
