"""
estimate_feedback_law.py  —  CADENCE pipeline, Module 3
=======================================================
Recover the load-dependent negative-feedback law from the DECODED states:

        P(SUSTAINED_HIGH -> REFRACTORY | L) = sigmoid(b0 + b1 * L)

`b1 > 0` is the quantitative signature of negative feedback: the longer the
system has been sitting in the high-calcium state, the more likely it is to
switch itself off. `b1 ~ 0` means no feedback. Recovering b1 from data that was
generated by a KNOWN b1 is the estimator-validation step the whole project rests
on — and it is what the Module 4 controller will later act through.

WHY A LOAD VARIABLE AT ALL (the semi-Markov problem)
-----------------------------------------------------
A plain HMM has a CONSTANT transition matrix: P(high -> refractory) is the same
whether the cell just entered the high state or has been stuck there for a
minute. That is exactly wrong for the biology we care about — the feedback is
cumulative. Rather than abandon the HMM, we keep it for state *estimation* and
model the feedback explicitly as a function of an accumulated load:

    L[t] = decay * L[t-1] + 1{state[t] == SUSTAINED_HIGH}

This is a causal exponential accumulator: it rises while the cell is in the high
state and decays otherwise, so it encodes "how much recent high-calcium burden
has this cell taken on." Causal = uses only past and present frames, never the
future, so the same quantity can be computed live by the controller.

CHOOSING THE DECAY HONESTLY
---------------------------
The simulator uses decay = 0.92, but we are not allowed to just know that (on
real data nobody hands you the constant). We select it by PROFILE LIKELIHOOD:
scan a grid, fit the logistic model at each value, keep the decay whose fit has
the highest log-likelihood. The selected value is reported so the reader can see
whether the estimator found the truth on its own.

INFERENCE
---------
Logistic regression by maximum likelihood, hand-implemented on scipy.optimize
(sklearn is outside the dependency budget). Two uncertainty estimates:

  1) Wald CI from the inverse observed-information matrix. Fast, but it assumes
     every frame is an independent observation, which is FALSE here — frames
     within a trace are strongly autocorrelated, so Wald CIs are too narrow.
  2) CLUSTER BOOTSTRAP over whole traces (resample cells with replacement, refit).
     This respects the fact that the independent experimental unit is the CELL,
     not the frame. This is the CI we report as primary; the Wald interval is
     printed alongside purely to show how much the naive version would mislead.

THE ATTENUATION PROBLEM (reported, not hidden)
----------------------------------------------
Module 2 recovers REFRACTORY at only ~38% recall. Feeding noisy state labels into
this regression biases b1 TOWARD ZERO (classical attenuation from measurement
error in the outcome variable). So we fit the law THREE ways and print all three:

    (a) from INFERRED states  -> what the real pipeline achieves end-to-end
    (b) from TRUE states      -> an oracle upper bound; isolates how much damage
                                 state-estimation error alone is doing
    (c) ground-truth b1        -> the number the simulator actually used

If (a) < (b) < (c), we know precisely where the loss comes from and can say so
instead of quietly reporting the best-looking number.

NOTE ON SCALE: b1 is not expected to land exactly on 0.9 even in the oracle fit,
because L is rebuilt from decoded state runs whose durations differ slightly from
the simulator's; rescaling L rescales b1 inversely. The scientific claim being
tested is not "b1 == 0.9" but the falsifiable pair:
        b1_intact > 0   AND   b1_intact > b1_blocked ~ 0.
"""

import argparse
import os

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.optimize import minimize

STATE_NAMES = ["QUIESCENT", "OSCILLATORY", "SUSTAINED_HIGH", "REFRACTORY"]
HIGH, REFRACTORY = 2, 3

# Ground truth baked into generate_synthetic.py, for reporting only - never used
# to fit anything.
TRUE_BETA1 = {"intact": 0.9, "blocked": 0.02}
TRUE_BETA0 = -3.0


# --------------------------------------------------------------------------- #
# Load accumulator
# --------------------------------------------------------------------------- #
def compute_load(states, decay):
    """
    Causal exponential accumulator over time spent in SUSTAINED_HIGH.

        L[t] = decay * L[t-1] + 1{states[t] == HIGH}

    Returns L aligned with `states`. L[t] includes the current frame's
    contribution, matching the simulator's convention (the load that is "in
    effect" when the cell decides whether to switch off at frame t).
    """
    L = np.empty(len(states), dtype=float)
    acc = 0.0
    for t, s in enumerate(states):
        acc = acc * decay + (1.0 if s == HIGH else 0.0)
        L[t] = acc
    return L


def build_transition_dataset(df, state_col, decay):
    """
    Extract the (load, did_it_switch_off) pairs the logistic model is fit to.

    We look ONLY at frames where the cell is currently in SUSTAINED_HIGH — those
    are the frames at which the feedback law is defined — and ask whether the
    NEXT frame is REFRACTORY.

    Returns (L, y, trace_ids) where trace_ids is kept so the bootstrap can
    resample whole cells.
    """
    Ls, ys, tids = [], [], []
    for tid, g in df.groupby("trace_id", sort=True):
        g = g.sort_values("time_s")
        s = g[state_col].to_numpy()
        L = compute_load(s, decay)

        at_high = s[:-1] == HIGH               # frames where the law applies
        if not at_high.any():
            continue
        switched = (s[1:] == REFRACTORY)       # did it switch off next frame?
        Ls.append(L[:-1][at_high])
        ys.append(switched[at_high].astype(float))
        tids.append(np.full(at_high.sum(), tid))

    if not Ls:
        return np.array([]), np.array([]), np.array([])
    return np.concatenate(Ls), np.concatenate(ys), np.concatenate(tids)


# --------------------------------------------------------------------------- #
# Logistic regression by maximum likelihood
# --------------------------------------------------------------------------- #
def _nll_and_grad(beta, X, y):
    """
    Negative log-likelihood and gradient for logistic regression.
    Uses logaddexp for numerical stability instead of log(1+exp(z)) directly.
    """
    z = X @ beta
    nll = np.sum(np.logaddexp(0.0, z) - y * z)
    p = 1.0 / (1.0 + np.exp(-z))
    grad = X.T @ (p - y)
    return nll, grad


def fit_logistic(L, y):
    """
    MLE fit of P(y=1 | L) = sigmoid(b0 + b1*L).
    Returns (beta, loglik, cov) where cov is the inverse observed information
    (used for the Wald CI).
    """
    X = np.column_stack([np.ones_like(L), L])
    res = minimize(_nll_and_grad, np.zeros(2), args=(X, y),
                   jac=True, method="BFGS")
    beta = res.x
    loglik = -res.fun

    # observed information: X' W X, with W = diag(p(1-p))
    z = X @ beta
    p = 1.0 / (1.0 + np.exp(-z))
    W = p * (1.0 - p)
    info = X.T @ (X * W[:, None])
    try:
        cov = np.linalg.inv(info)
    except np.linalg.LinAlgError:
        cov = np.full((2, 2), np.nan)
    return beta, loglik, cov


def select_decay(df, state_col, grid):
    """
    Choose the load decay by profile likelihood: refit the logistic model at each
    candidate decay and keep the best-fitting one. This is how we avoid smuggling
    in the simulator's 0.92.
    """
    best = (None, -np.inf, None)
    for d in grid:
        L, y, _ = build_transition_dataset(df, state_col, d)
        if len(L) < 20 or y.sum() < 5:
            continue
        _, ll, _ = fit_logistic(L, y)
        if ll > best[1]:
            best = (d, ll, None)
    return best[0]


def bootstrap_b1(df, state_col, decay, n_boot=400, seed=0):
    """
    CLUSTER bootstrap: resample whole traces with replacement and refit.

    Frames within a trace are autocorrelated, so treating frames as the
    resampling unit would badly understate uncertainty. The cell is the
    independent experimental unit, so the cell is what we resample.
    """
    rng = np.random.default_rng(seed)
    trace_ids = df["trace_id"].unique()
    by_trace = {tid: g for tid, g in df.groupby("trace_id", sort=True)}

    out = []
    for _ in range(n_boot):
        picked = rng.choice(trace_ids, size=len(trace_ids), replace=True)
        # relabel so repeated draws are treated as distinct cells
        parts = []
        for new_id, tid in enumerate(picked):
            g = by_trace[tid].copy()
            g["trace_id"] = new_id
            parts.append(g)
        boot_df = pd.concat(parts, ignore_index=True)

        L, y, _ = build_transition_dataset(boot_df, state_col, decay)
        if len(L) < 20 or y.sum() < 3:
            continue
        beta, _, _ = fit_logistic(L, y)
        out.append(beta[1])
    return np.array(out)


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #
def analyse(df, condition, state_col, decay, n_boot, seed, label):
    L, y, _ = build_transition_dataset(df, state_col, decay)
    if len(L) == 0:
        print(f"  [{label}] no SUSTAINED_HIGH frames found - cannot fit.")
        return None

    beta, ll, cov = fit_logistic(L, y)
    b0, b1 = beta
    se_b1 = np.sqrt(cov[1, 1]) if np.isfinite(cov[1, 1]) else np.nan
    wald_lo, wald_hi = b1 - 1.96 * se_b1, b1 + 1.96 * se_b1

    boots = bootstrap_b1(df, state_col, decay, n_boot=n_boot, seed=seed)
    if len(boots):
        blo, bhi = np.percentile(boots, [2.5, 97.5])
    else:
        blo = bhi = np.nan

    print(f"  [{label}]  n_high_frames={len(L)}  n_switch_events={int(y.sum())}")
    print(f"      b0 = {b0:+.3f}")
    print(f"      b1 = {b1:+.4f}   "
          f"cluster-bootstrap 95% CI [{blo:+.4f}, {bhi:+.4f}]   <-- reported")
    print(f"                        naive Wald 95% CI [{wald_lo:+.4f}, {wald_hi:+.4f}]"
          f"  (too narrow: assumes independent frames)")
    return {"condition": condition, "label": label, "b0": b0, "b1": b1,
            "boot": boots, "ci": (blo, bhi), "L": L, "y": y, "decay": decay}


def plot_feedback_curves(results, out_png):
    """
    The headline figure: recovered feedback law, intact vs blocked, with
    bootstrap uncertainty and the binned empirical switch rate overlaid so the
    reader can see the fit is not just a smooth line through nothing.
    """
    fig, ax = plt.subplots(figsize=(7.4, 5.0))
    colors = {"intact": "#1f77b4", "blocked": "#d62728"}

    for r in results:
        if r is None:
            continue
        cond = r["condition"]
        c = colors.get(cond, "gray")
        L, y = r["L"], r["y"]
        grid = np.linspace(0, np.percentile(L, 99), 200)

        # bootstrap band: recompute the curve for each bootstrap b1
        curves = []
        for b1b in r["boot"]:
            curves.append(1 / (1 + np.exp(-(r["b0"] + b1b * grid))))
        if curves:
            curves = np.array(curves)
            lo, hi = np.percentile(curves, [2.5, 97.5], axis=0)
            ax.fill_between(grid, lo, hi, color=c, alpha=0.18, lw=0)

        fit = 1 / (1 + np.exp(-(r["b0"] + r["b1"] * grid)))
        ax.plot(grid, fit, color=c, lw=2,
                label=f"{cond}: b1={r['b1']:+.3f} "
                      f"[{r['ci'][0]:+.3f}, {r['ci'][1]:+.3f}]")

        # binned empirical rate
        edges = np.linspace(0, np.percentile(L, 99), 9)
        idx = np.digitize(L, edges) - 1
        for b in range(len(edges) - 1):
            m = idx == b
            if m.sum() > 30:
                ax.plot(0.5 * (edges[b] + edges[b + 1]), y[m].mean(),
                        "o", color=c, ms=5, mec="white", mew=0.8)

    ax.set_xlabel("calcium load  L  (causal exponential accumulator)")
    ax.set_ylabel("P(SUSTAINED_HIGH -> REFRACTORY)")
    ax.set_title("Recovered negative-feedback law\n"
                 "b1 > 0 = the feedback signature; dots = binned empirical rate")
    ax.legend(loc="upper left", fontsize=9)
    ax.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(out_png, dpi=150)
    plt.close(fig)


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser(description="Recover the load-dependent feedback law.")
    ap.add_argument("--intact", default="data/decoded_intact.csv")
    ap.add_argument("--blocked", default="data/decoded_blocked.csv")
    ap.add_argument("--n_boot", type=int, default=400)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--fig_out", default="figures/feedback_law.png")
    args = ap.parse_args()

    decay_grid = np.round(np.arange(0.80, 0.99, 0.01), 2)
    results_inferred, results_true = [], []

    for cond, path in (("intact", args.intact), ("blocked", args.blocked)):
        print(f"\n=== {cond} ===")
        df = pd.read_csv(path)

        # decay chosen by profile likelihood on the INFERRED states (what the
        # real pipeline has access to), then reused for the oracle fit so the two
        # are directly comparable.
        decay = select_decay(df, "inferred_state", decay_grid)
        print(f"  load decay selected by profile likelihood: {decay}"
              f"   (simulator used 0.92)")

        r_inf = analyse(df, cond, "inferred_state", decay,
                        args.n_boot, args.seed, "INFERRED states (end-to-end)")
        r_true = analyse(df, cond, "true_state", decay,
                         args.n_boot, args.seed, "TRUE states (oracle bound)")
        print(f"      ground truth b1 used by simulator: {TRUE_BETA1[cond]:+.3f}")

        results_inferred.append(r_inf)
        results_true.append(r_true)

    # ---- the falsifiable comparison: intact vs blocked -------------------- #
    print("\n=== HYPOTHESIS TEST: b1_intact > b1_blocked ===")
    for tag, res in (("INFERRED (end-to-end)", results_inferred),
                     ("TRUE (oracle)", results_true)):
        a, b = res[0], res[1]
        if a is None or b is None or not len(a["boot"]) or not len(b["boot"]):
            print(f"  [{tag}] insufficient data.")
            continue
        n = min(len(a["boot"]), len(b["boot"]))
        diff = a["boot"][:n] - b["boot"][:n]
        lo, hi = np.percentile(diff, [2.5, 97.5])
        p_one_sided = float(np.mean(diff <= 0))
        print(f"  [{tag}]  b1_intact - b1_blocked = {a['b1'] - b['b1']:+.4f}"
              f"   95% CI [{lo:+.4f}, {hi:+.4f}]"
              f"   one-sided p = {p_one_sided:.4f}")
        verdict = "SUPPORTED" if lo > 0 else "NOT supported"
        print(f"      -> feedback signature {verdict} "
              f"(CI {'excludes' if lo > 0 else 'includes'} zero)")

    os.makedirs(os.path.dirname(args.fig_out), exist_ok=True)
    plot_feedback_curves([r for r in results_inferred if r], args.fig_out)
    print(f"\nwrote {args.fig_out}")
    print("Module 3 complete. Next: controller.py (CADENCE control policy).")


if __name__ == "__main__":
    main()
